/**
 * GuardCardCheck.com — State Registry
 * All 10 confirmed Day-1 states with regulatory metadata,
 * license type definitions, and portal access configuration.
 * 
 * Access Tiers:
 *   OFFICIAL_API   = Formal, documented API (CA only)
 *   PORTAL_SCRAPE  = Public web portal, programmatic access via HTTP
 *   BULK_RECORDS   = Public records bulk data (FL — strongest records law in US)
 */

const ACCESS_TYPE = {
  OFFICIAL_API:  'official_api',
  PORTAL_SCRAPE: 'portal_scrape',
  BULK_RECORDS:  'bulk_records',
};

const STATES = {
  CA: {
    code: 'CA',
    name: 'California',
    fullName: 'State of California',
    flag: '🏴',
    agency: {
      name: 'Bureau of Security and Investigative Services (BSIS)',
      parent: 'Department of Consumer Affairs (DCA)',
      website: 'https://www.bsis.ca.gov',
      phone: '(800) 952-5210',
      enforcement: 'Active — working without license is a misdemeanor; PPO violations up to $10,000/day',
    },
    access: {
      type: ACCESS_TYPE.OFFICIAL_API,
      portalUrl: 'https://www.bsis.ca.gov/onlineservices/verify.shtml',
      apiBase: 'https://www.dca.ca.gov/webapps/bsis',
      notes: 'Formal DCA developer API. Apply via DCA Open Data portal.',
    },
    licenses: {
      GUARD_CARD: {
        code: 'G',
        name: 'Guard Card',
        description: 'Security Guard Registration',
        prefix: 'G',
        armedCapable: false,
        renewalYears: 2,
        individual: true,
      },
      FIREARM_PERMIT: {
        code: 'FE',
        name: 'Exposed Firearm Permit',
        description: 'Permits open carry while on duty',
        prefix: 'FE',
        armedCapable: true,
        renewalYears: 2,
        individual: true,
      },
      FIREARM_QUAL: {
        code: 'FQ',
        name: 'Firearm Qualification Card',
        description: 'Weapon-specific qualification',
        prefix: 'FQ',
        armedCapable: true,
        renewalYears: 1,
        individual: true,
      },
      PPO: {
        code: 'PPO',
        name: 'Private Patrol Operator',
        description: 'Business license for security companies contracting guards',
        prefix: 'PPO',
        armedCapable: false,
        renewalYears: 2,
        individual: false, // company license
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName'],
    licenseFormat: /^(G|FE|FQ|PPO)\d{5,8}$/i,
    notes: 'First state. CA BSIS is the regulatory gold standard — all other states measured against it.',
    launched: true,
  },

  FL: {
    code: 'FL',
    name: 'Florida',
    fullName: 'State of Florida',
    agency: {
      name: 'Division of Licensing',
      parent: 'Florida Department of Agriculture and Consumer Services (FDACS)',
      website: 'https://www.fdacs.gov/Business-Services/Private-Security-Licenses',
      phone: '(850) 245-5491',
      enforcement: 'Working without Class D = 1st-degree misdemeanor, $2,500 fine, 5-year industry ban',
    },
    access: {
      type: ACCESS_TYPE.BULK_RECORDS,
      portalUrl: 'https://licensing.fdacs.gov/access/individual.aspx',
      bulkRequestEmail: 'fdacs-licensing@fdacs.gov',
      publicRecordsLaw: 'Chapter 119, Florida Statutes — one of the broadest in the US',
      notes: 'Public portal for individual lookups + bulk data available via Ch. 119 public records request.',
    },
    licenses: {
      CLASS_D: {
        code: 'D',
        name: 'Class D Security Officer License',
        description: 'Unarmed security officer — 40 hours training required',
        prefix: 'D',
        armedCapable: false,
        renewalYears: 2,
        individual: true,
      },
      CLASS_G: {
        code: 'G',
        name: 'Class G Statewide Firearms License',
        description: 'Armed officer permit — separate from Class D, additional training',
        prefix: 'G',
        armedCapable: true,
        renewalYears: 2,
        individual: true,
      },
      MANAGER_MB: {
        code: 'MB',
        name: 'Manager Security Agency (MB)',
        description: 'Qualifying manager for licensed security companies',
        prefix: 'MB',
        armedCapable: false,
        renewalYears: 2,
        individual: false,
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName', 'licenseType'],
    licenseFormat: /^(D|G|MB|MA|M|MR)\d{5,8}$/i,
    notes: 'Mirror of CA structure (D≈Guard Card, G≈Firearm Permit). FL public records law makes bulk data access straightforward.',
    launched: false,
  },

  TX: {
    code: 'TX',
    name: 'Texas',
    fullName: 'State of Texas',
    agency: {
      name: 'Private Security Bureau (PSB)',
      parent: 'Texas Department of Public Safety (DPS)',
      website: 'https://www.dps.texas.gov/section/private-security',
      phone: '(512) 424-7293',
      enforcement: 'Unlicensed operation = Class A misdemeanor up to felony depending on circumstance',
    },
    access: {
      type: ACCESS_TYPE.PORTAL_SCRAPE,
      portalUrl: 'https://tops.dps.texas.gov/PSBPortalPRD/PSB_VerifyLicense.aspx',
      systemName: 'TOPS (Texas Online Private Security)',
      notes: 'Modern web portal — structured HTML responses, consistent format for programmatic access.',
    },
    licenses: {
      LEVEL_II: {
        code: 'L2',
        name: 'Level II Security Officer',
        description: 'Unarmed security officer — 6 hours basic training',
        armedCapable: false,
        renewalYears: 2,
        individual: true,
      },
      LEVEL_III: {
        code: 'L3',
        name: 'Level III Security Officer Commission',
        description: 'Armed — 40 hours training + weapons qualification',
        armedCapable: true,
        renewalYears: 2,
        individual: true,
      },
      LEVEL_IV: {
        code: 'L4',
        name: 'Level IV Personal Protection Officer',
        description: 'Executive protection / bodyguard license',
        armedCapable: true,
        renewalYears: 2,
        individual: true,
      },
      CLASS_B: {
        code: 'B',
        name: 'Class B Security Company License',
        description: 'Business license for security companies',
        armedCapable: false,
        renewalYears: 1,
        individual: false,
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName'],
    licenseFormat: /^\d{6,8}$/,
    notes: 'Tiered system (II/III/IV) means your product tracks level, not just active/expired — higher value than CA single-tier.',
    launched: false,
  },

  IL: {
    code: 'IL',
    name: 'Illinois',
    fullName: 'State of Illinois',
    agency: {
      name: 'Division of Professional Regulation',
      parent: 'Illinois Department of Financial and Professional Regulation (IDFPR)',
      website: 'https://idfpr.illinois.gov/profs/securitycont.html',
      phone: '(312) 814-6910',
      enforcement: '$10,000 fines per violation for knowingly hiring unlicensed personnel after warning',
    },
    access: {
      type: ACCESS_TYPE.PORTAL_SCRAPE,
      portalUrl: 'https://online-dfpr.micropact.com/lookup/licenselookup.aspx',
      openDataPortal: 'https://data.illinois.gov',
      notes: 'IDFPR license lookup + Illinois has active open data program publishing professional license datasets.',
    },
    licenses: {
      PERC: {
        code: 'PERC',
        name: 'Permanent Employee Registration Card (PERC)',
        description: 'Required for ALL security guards — unarmed and armed',
        armedCapable: false,
        renewalYears: 3,
        individual: true,
      },
      FCC: {
        code: 'FCC',
        name: 'Firearm Control Card (FCC)',
        description: 'Armed guard endorsement — additional 20-hour firearms course + range qual',
        armedCapable: true,
        renewalYears: 3,
        individual: true,
      },
      PSC_AGENCY: {
        code: 'PSC',
        name: 'Private Security Contractor Agency',
        description: 'Company license for security agencies',
        armedCapable: false,
        renewalYears: 1,
        individual: false,
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName', 'licenseType'],
    licenseFormat: /^\d{6,10}$/,
    notes: 'PERC + FCC = cleanest two-credential structure outside of CA. High enforcement = high customer demand.',
    launched: false,
  },

  VA: {
    code: 'VA',
    name: 'Virginia',
    fullName: 'Commonwealth of Virginia',
    agency: {
      name: 'Private Security Services Division',
      parent: 'Virginia Department of Criminal Justice Services (DCJS)',
      website: 'https://www.dcjs.virginia.gov/private-security-organization/private-security',
      phone: '(804) 786-4700',
      enforcement: 'Active — DCJS can revoke licenses, refer criminal prosecution',
    },
    access: {
      type: ACCESS_TYPE.PORTAL_SCRAPE,
      portalUrl: 'https://www.cms.dcjs.virginia.gov/GLSuiteWeb/Clients/VADCJS/Public/IndividualVerification/Search.aspx',
      notes: 'Structured GLSuite platform used by multiple states. Consistent HTML output. Search by name or license number.',
    },
    licenses: {
      UNARMED_REG: {
        code: 'UNARMED',
        name: 'Unarmed Security Officer Registration',
        description: 'Base registration for unarmed guards',
        armedCapable: false,
        renewalYears: 2,
        individual: true,
      },
      ARMED_REG: {
        code: 'ARMED',
        name: 'Armed Security Officer Registration with Firearms Certification',
        description: 'Includes FCC endorsement for armed duty',
        armedCapable: true,
        renewalYears: 2,
        individual: true,
      },
      BUSINESS_LICENSE: {
        code: 'BIZ',
        name: 'Private Security Business License',
        description: 'Company license required for security firms',
        armedCapable: false,
        renewalYears: 2,
        individual: false,
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName'],
    licenseFormat: /^\d{5,8}$/,
    notes: 'DCJS is arguably the cleanest regulatory analog to BSIS — dedicated criminal justice oversight of private security.',
    launched: false,
  },

  NV: {
    code: 'NV',
    name: 'Nevada',
    fullName: 'State of Nevada',
    agency: {
      name: 'Private Investigators Licensing Board (PILB)',
      parent: 'State of Nevada',
      website: 'https://pilb.nv.gov',
      phone: '(702) 486-3009',
      enforcement: 'Active — NRS 648.060 requires all private patrol businesses to be licensed',
    },
    access: {
      type: ACCESS_TYPE.PORTAL_SCRAPE,
      portalUrl: 'https://pilbonbaseweb.nv.gov/publicAccess/',
      notes: 'PILB public document search (OBPA). Wildcard rules: ~3 letters + * for names; prefix + * for license #.',
    },
    licenses: {
      WORK_CARD: {
        code: 'WC',
        name: 'Security Guard Work Card',
        description: 'Base registration — exam required (100% pass score)',
        armedCapable: false,
        renewalYears: 2,
        individual: true,
      },
      FIREARMS_CERT: {
        code: 'FC',
        name: 'Firearms Certification Card',
        description: 'Armed endorsement — 13 hours training (8 classroom + 5 range), valid 5 years, 6-month range requalification',
        armedCapable: true,
        renewalYears: 5,
        individual: true,
      },
      PPO_LICENSE: {
        code: 'PPO',
        name: 'Private Patrol Officer Business License',
        description: 'Required for all businesses advertising private patrol services (NRS 648.060)',
        armedCapable: false,
        renewalYears: 1,
        individual: false,
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName'],
    licenseFormat: /^(WC|FC)?\d{5,8}$/i,
    notes: 'Smaller population but Las Vegas casino/event security is enormous and extremely compliance-conscious.',
    launched: true,
  },

  OR: {
    code: 'OR',
    name: 'Oregon',
    fullName: 'State of Oregon',
    agency: {
      name: 'Private Security Section',
      parent: 'Department of Public Safety Standards and Training (DPSST)',
      website: 'https://www.oregon.gov/dpsst/ps/pages/iris.aspx',
      phone: '(503) 378-2100',
      enforcement: 'Active enforcement — DPSST can suspend, revoke, and issue civil penalties',
    },
    access: {
      type: ACCESS_TYPE.PORTAL_SCRAPE,
      portalUrl: 'https://www.oregon.gov/dpsst/ps/pages/iris.aspx',
      systemName: 'IRIS (Internet Records Information System)',
      notes: 'IRIS is a dedicated public records system for OR DPSST. Well-structured HTML output.',
    },
    licenses: {
      SECURITY_CERT: {
        code: 'SEC',
        name: 'Security Professional Certification',
        description: 'Unarmed — 24 hours pre-assignment training',
        armedCapable: false,
        renewalYears: 2,
        individual: true,
      },
      ARMED_CERT: {
        code: 'ASEC',
        name: 'Armed Security Professional Certification',
        description: 'Armed endorsement — additional 24-hour basic firearms course + written exam + range qual',
        armedCapable: true,
        renewalYears: 2,
        individual: true,
      },
      COMPANY_REG: {
        code: 'COMP',
        name: 'Private Security Company Registration',
        description: 'Required for security companies operating in Oregon',
        armedCapable: false,
        renewalYears: 1,
        individual: false,
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName'],
    licenseFormat: /^\d{5,8}$/,
    notes: 'Solid Pacific Northwest market. DPSST IRIS is purpose-built for public verification.',
    launched: false,
  },

  WA: {
    code: 'WA',
    name: 'Washington',
    fullName: 'State of Washington',
    agency: {
      name: 'Private Security Section',
      parent: 'Washington State Department of Licensing (DOL)',
      website: 'https://www.dol.wa.gov/business/privatesecurity/',
      phone: '(360) 664-6611',
      enforcement: 'Active — DOL can suspend/revoke, refer to AG for prosecution',
    },
    access: {
      type: ACCESS_TYPE.PORTAL_SCRAPE,
      portalUrl: 'https://fortress.wa.gov/dol/dolprod/bpdLicenseQuery/',
      openDataPortal: 'https://data.wa.gov',
      notes: 'WA DOL license portal + Washington has a strong open data program. Annual refresher training requirement creates recurring verification need.',
    },
    licenses: {
      GUARD_LICENSE: {
        code: 'SG',
        name: 'Security Guard License',
        description: 'Unarmed guard — fingerprinting and background check required',
        armedCapable: false,
        renewalYears: 2,
        individual: true,
      },
      ARMED_ENDORSEMENT: {
        code: 'ASG',
        name: 'Armed Security Guard Endorsement',
        description: 'Armed endorsement — employer-owned firearms required, annual refresher',
        armedCapable: true,
        renewalYears: 2,
        individual: true,
      },
      SECURITY_AGENCY: {
        code: 'SA',
        name: 'Security Agency License',
        description: 'Company license — required for all security service businesses',
        armedCapable: false,
        renewalYears: 1,
        individual: false,
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName'],
    licenseFormat: /^\d{5,10}$/,
    notes: 'Pacific Northwest tech/event security market. Annual refresher requirement = guards need re-verification annually = recurring value.',
    launched: false,
  },

  AZ: {
    code: 'AZ',
    name: 'Arizona',
    fullName: 'State of Arizona',
    agency: {
      name: 'Licensing Unit',
      parent: 'Arizona Department of Public Safety (DPS)',
      website: 'https://www.azdps.gov/services/public/licensing',
      phone: '(602) 223-2361',
      enforcement: 'Active — ARS §32-2622 outlines precluding offenses; DPS investigates complaints',
    },
    access: {
      type: ACCESS_TYPE.PORTAL_SCRAPE,
      portalUrl: 'https://psp.azdps.gov/securityLicense/securityStatus',
      notes:
        'Verification uses the legacy public inquiry AJAX (same license data as the AZDPS Public Services Portal).',
    },
    licenses: {
      UNARMED_GUARD: {
        code: 'UAG',
        name: 'Unarmed Security Guard Registration',
        description: 'Unarmed — 8 hours training required',
        armedCapable: false,
        renewalYears: 2,
        individual: true,
      },
      ARMED_GUARD: {
        code: 'AG',
        name: 'Armed Security Guard Registration',
        description: 'Armed — additional 16-hour DPS-approved firearms training course',
        armedCapable: true,
        renewalYears: 2,
        individual: true,
      },
      AGENCY_LICENSE: {
        code: 'SGA',
        name: 'Security Guard Agency License',
        description: 'Required for all security guard agencies — Qualifying Party designation required',
        armedCapable: false,
        renewalYears: 2,
        individual: false,
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName'],
    licenseFormat: /^\d{5,9}$/,
    notes: 'Phoenix/Scottsdale large event security market. Public inquiry app at webapps.azdps.gov returns status including expiration.',
    launched: false,
  },

  NC: {
    code: 'NC',
    name: 'North Carolina',
    fullName: 'State of North Carolina',
    agency: {
      name: 'Private Protective Services Board (PPSB)',
      parent: 'NC Department of Public Safety',
      website: 'https://www.ncdps.gov/about-dps/boards-and-commissions/private-protective-services-board',
      phone: '(919) 788-5320',
      enforcement: 'Active — Board can revoke/suspend licenses and refer for criminal prosecution under GS 74C',
    },
    access: {
      type: ACCESS_TYPE.PORTAL_SCRAPE,
      portalUrl: 'https://ppsapplication.permitium.com/publicapp/actives/licensee/list',
      systemName: 'Permitium (NC PPSB)',
      notes: 'NC uses Permitium platform which has a public active licensee list. Well-structured REST-style URLs.',
    },
    licenses: {
      UNARMED_REG: {
        code: 'UNARMED',
        name: 'Unarmed Security Guard Registration Card',
        description: 'Unarmed — 16 hours classroom required; company registers employee',
        armedCapable: false,
        renewalYears: 1,
        individual: true,
      },
      FIREARM_PERMIT: {
        code: 'FRP',
        name: 'Firearm Registration Permit',
        description: 'Armed — belongs to the State, expires upon termination. Company must register within 30 days.',
        armedCapable: true,
        renewalYears: 1,
        individual: true,
      },
      PATROL_LICENSE: {
        code: 'GPL',
        name: 'Guard and Patrol Business License',
        description: 'Company license — qualifying agent required at all times',
        armedCapable: false,
        renewalYears: 1,
        individual: false,
      },
    },
    searchFields: ['licenseNumber', 'firstName', 'lastName'],
    licenseFormat: /^\d{5,8}$/,
    notes: 'NC Firearm Registration Permit is unique — it belongs to the State and expires on job termination. This creates constant re-verification need for armed guards.',
    launched: false,
  },
};

// Helper: get all active states
const getActiveStates = () => Object.values(STATES);
const getLaunchedStates = () => Object.values(STATES).filter(s => s.launched);
const getState = (code) => STATES[code.toUpperCase()] || null;
const getStateList = () => Object.values(STATES).map(s => ({
  code: s.code,
  name: s.name,
  launched: s.launched,
  agency: s.agency.name,
  licenseTypes: Object.values(s.licenses).filter(l => l.individual).map(l => l.name),
}));

module.exports = { STATES, ACCESS_TYPE, getActiveStates, getLaunchedStates, getState, getStateList };
